call npm i archiver -s
call npm i cookie-parser -s
call npm i directory-tree -s
call npm i dotenv -s
call npm i express -s
call npm i fs-extra -s
call npm i jsonwebtoken -s
call npm i lowdb -s
call npm i mongodb -s
call npm i multer -s
call npm i mysql2 -s
call npm i nodemailer -s
call npm i sequelize -s
call npm i sqlite3 -s
call npm i ws -s
call npm i vite -s
call npm i vite-plugin-handlebars -s
call npm i bootstrap -s
call npm i bootstrap-icons -s
call npm i sass -s
call npm i sass-loader -s
call npm i vite-plugin-nunjucks -s
call npm i vite-plugin-static-copy -s
call npm i feather-icons -s
call npm i sweetalert2 -s
call npm i @sweetalert2/theme-dark -s
